[package]
name = "digger-tauri"
version = "0.0.1"
authors = ["wt-7"]
license = "MIT"
repository = "github.com/wt-7/digger"
edition = "2021"
publish = false


[build-dependencies]
tauri-build = { version = "1.4", features = [] }


[dependencies]
tauri = { version = "1.4", features = [
    "os-all",
    "window-unmaximize",
    "window-maximize",
    "window-start-dragging",
    "dialog-open",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.75"
jwalk = "0.8.1"
rayon = "1.7.0"
zip = "0.6.6"
quick-xml = "0.30.0"
aho-corasick = "1.1.1"
time = { version = "0.3.28", features = [
    "serde",
    "parsing",
    "macros",
    "formatting",
] }
pdf-extract = "0.7.2"
tempfile = "3.9.0"
line-numbers = "0.3.0"
ignore = "0.4.22"
crossbeam-channel = "0.5.12"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
num_cpus = "1.16.0"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
